"""add columns to celery_record

Revision ID: 051eecdf2029
Revises: f948d61d65a8
Create Date: 2018-08-13 16:14:36.515933

"""

# revision identifiers, used by Alembic.
revision = '051eecdf2029'
down_revision = 'f948d61d65a8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_restart_rds', sa.Column('cur_pids', sa.String(length=100), nullable=True))
    op.add_column('celery_restart_rds', sa.Column('old_pids', sa.String(length=100), nullable=True))
    op.add_column('celery_restart_rds', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('celery_restart_rds', sa.Column('is_restart', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('celery_restart_rds', 'status')
    op.drop_column('celery_restart_rds', 'old_pids')
    op.drop_column('celery_restart_rds', 'cur_pids')
    op.drop_column('celery_restart_rds', 'is_restart')
    # ### end Alembic commands ###
