"""add column to table tasks

Revision ID: 3e7850487eed
Revises: c2237b0f2bba
Create Date: 2018-08-22 15:25:52.366541

"""

# revision identifiers, used by Alembic.
revision = '3e7850487eed'
down_revision = 'c2237b0f2bba'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_record', 'step')
    op.add_column('tasks', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_active')
    op.add_column('alarm_record', sa.Column('step', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
