"""create collect rule table

Revision ID: 7bca6dd7d589
Revises: e6979f6d1e3f
Create Date: 2018-08-02 18:03:25.044876

"""

# revision identifiers, used by Alembic.
revision = '7bca6dd7d589'
down_revision = 'e6979f6d1e3f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect_rules',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('pro_name', sa.String(length=50), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_origin_config',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro_name', sa.String(length=50), nullable=True),
    sa.Column('db_name', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('md_config',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('range', sa.String(length=90), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables_group', type_='unique')
    op.drop_constraint(None, 'tables_group', type_='unique')
    op.alter_column('tables_group', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='unique')
    op.create_index('_customer_location_uc', 'tables', ['database_id', 'schema', 'table_name'], unique=True)
    op.alter_column('tables', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'table_columns', type_='unique')
    op.drop_constraint(None, 'sql_metrics', type_='unique')
    op.drop_constraint(None, 'mpage_mproject', type_='foreignkey')
    op.drop_constraint(None, 'mpage_mproject', type_='foreignkey')
    op.create_index('index_project', 'mpage_mproject', ['mproject_id'], unique=False)
    op.create_index('index_page', 'mpage_mproject', ['mpage_id'], unique=False)
    op.add_column('metrics', sa.Column('datasource_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.create_foreign_key('metrics_ibfk_1', 'metrics', 'datasources', ['datasource_name'], ['datasource_name'])
    op.drop_constraint(None, 'metrics', type_='unique')
    op.drop_column('metrics', 'warning_text')
    op.drop_column('metrics', 'datasource_id')
    op.drop_constraint(None, 'melement_mpage_mproject', type_='foreignkey')
    op.drop_constraint(None, 'melement_mpage_mproject', type_='foreignkey')
    op.alter_column('melement_mpage_mproject', 'mpage_mproject_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('melement_mpage_mproject', 'melement_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('m_project', 'status',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_page', 'status',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_page', 'del_status',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_element', 'status',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_element', 'del_status',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'datasources', type_='unique')
    op.create_index('datasource_name', 'datasources', ['datasource_name'], unique=True)
    op.add_column('columns', sa.Column('datasource_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'columns', type_='foreignkey')
    op.create_foreign_key('columns_ibfk_3', 'columns', 'datasources', ['datasource_name'], ['datasource_name'])
    op.drop_constraint(None, 'columns', type_='unique')
    op.drop_column('columns', 'datasource_id')
    op.drop_constraint(None, 'column_owners', type_='foreignkey')
    op.drop_constraint(None, 'column_owners', type_='foreignkey')
    op.drop_constraint(None, 'ab_user_role', type_='unique')
    op.drop_constraint(None, 'ab_permission_view_role', type_='unique')
    op.drop_constraint(None, 'ab_permission_view', type_='unique')
    op.drop_index('ti_dag_state', table_name='annotation')
    op.drop_table('annotation')
    op.drop_table('md_config')
    op.drop_table('data_origin_config')
    op.drop_table('collect_rules')
    op.drop_table('annotation_layer')
    # ### end Alembic commands ###
