"""add columns to collect rule

Revision ID: 9aebf53933c7
Revises: 460c70953ef5
Create Date: 2018-08-03 18:24:58.879498

"""

# revision identifiers, used by Alembic.
revision = '9aebf53933c7'
down_revision = '460c70953ef5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collect_record', 'collect_rule_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('collect_rules', sa.Column('collect_day', sa.DateTime(), nullable=True))
    op.add_column('collect_rules', sa.Column('partion_format', sa.String(length=60), nullable=True))
    op.add_column('collect_rules', sa.Column('sql_expression', sa.String(length=225), nullable=True))
    op.drop_column('collect_rules', 'start_time')
    op.drop_column('collect_rules', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collect_rules', sa.Column('end_time', mysql.DATETIME(), nullable=True))
    op.add_column('collect_rules', sa.Column('start_time', mysql.DATETIME(), nullable=True))
    op.drop_column('collect_rules', 'sql_expression')
    op.drop_column('collect_rules', 'partion_format')
    op.drop_column('collect_rules', 'collect_day')
    op.alter_column('collect_record', 'collect_rule_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
