"""add column to table validate_error_rule

Revision ID: c2237b0f2bba
Revises: e08becb1b350
Create Date: 2018-08-21 11:20:07.764763

"""

# revision identifiers, used by Alembic.
revision = 'c2237b0f2bba'
down_revision = 'e08becb1b350'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_table_name_uc', 'validate_error_rule', ['pro_name', 'table_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_table_name_uc', 'validate_error_rule', type_='unique')
    # ### end Alembic commands ###
